### ISSUE TITLE
Design a non-property-order-dependent method for hashing jobs to IDs.

### ISSUE THREAD

**Issue by Foxcapades** [VEuPathDB/lib-hash-id#3]
Presently the way jobs are hashed is by generating a JSON representation of that job.  This method relies heavily on the fact that code generated by the RAML generator has defined property orders for it's JSON representation.

This means, however, that without knowing the correct property order, two JSON structures with identical values but a different property ordering will have a different job IDs than one another.

There should be a way to generate a hash ID that examines the structure of what's being hashed reflectively rather than relying on the JSON serialization.

**Comment by ryanrdoherty** [comment]
Ellie, if you can accept using some org.json classes, FgpUtil has implemented this based on raw JSON.  One gotcha is that it assumes array order is important.  So it will treat arbitrarily ordered JSON objects as equal (if key/values are equal), but differently ordered arrays are considered different.   Might not be too hard to add a flag to treat arrays as sets, but would require ordering heterogeneous arrays' children somehow (e.g. objects first, then arrays, then strings, numbers, booleans), ordering each group... dunno- would be some work.  But this could get you started.  Or if differently ordered arrays can/should produce different hashes, then this will give you exactly what you want.

https://github.com/VEuPathDB/FgpUtil/blob/4e9441dbf2d3420ea0fe0bd68fdf89b818cc1742/Json/src/main/java/org/gusdb/fgputil/json/JsonUtil.java#L126

**Comment by Foxcapades** [comment]
Toyed around with some ideas for this over the weekend and came to the conclusion that this functionality does not belong in lib-hash-id.

The options for implementation I considered:

- reflectively recurse through all of the properties and compile them into a sorted tree of maps
    - Where do property names come from?
        - Values with the same purpose but different generated names wont align.
- reflectively recurse through all the properties and compile them into sorted lists
    - Unrelated things could generate the same hash ID if they happen to have the same values under properties of different purposes
- use custom annotations?
    - That starts us down a big path of functionality unrelated to the core purpose of lib-hash-id
- use external annotations?
    - lib-hash-id is a clean library with no external dependencies and should stay that way


I think a better approach would be to introduce a new, small library purpose built for generating hash ids from RAML pojos.

If we do this we can rely on the fact that we have jackson, and the properties will be annotated with the target names.

We can build a sorted tree of nodes based on the jackson representation of the POJO and generate the hash from that.
